"""
Django settings for usage project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(f1(v5vrr01bmlu%0fdrl+s_7ccj@bi*fge36#)_vm!nx2y_5n'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['manage.unifiedht.com', 'www.manage.unifiedht.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'voice',
    'core',
    'api',
    
    #crontab
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'usage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'usage_db',
#         'USER': 'apccrm',
#         'PASSWORD': 'Newapc09crm',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'raasbot',
        'USER' : 'postgres',
        'PASSWORD' : 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 
# AUTHENTICATION_BACKENDS = (
#         'django.contrib.auth.backends.RemoteUserBackend',
#         'django.contrib.auth.backends.ModelBackend',
# )

AUTH_USER_MODEL = 'core.User'

#twilio config
# --------------test --------------------------
# TWILIO_ACCOUNT_SID = 'AC2de62fbf27731a3be54704bcf8bfd1a9'
# TWILIO_AUTH_TOKEN = '02391c0fb421e7be01935cd340fe7008'
# ACCOUNT_API_KEY='SK826e5499011c896ef6535e0fc44aee7f'
# ACCOUNT_API_SECRET='1kONYml6G1frv1uBZAc9nKzl7urb4iHu'
# ---------------client -------------
TWILIO_ACCOUNT_SID = 'AC7920b6d90fdc17921b35032c86c033dd'
ACCOUNT_API_KEY = 'SK25cf2f8ffc8549e3cdcfc8b69d58d39a'
ACCOUNT_API_SECRET = 'MnNWgeEgpjsyw8L706nO9TNVReNCMriT'

#
TWILIO_SUBACCOUNT_SID = 'AC23d0c0440a87405738923a9719dcd82f'
SUBACCOUNT_API_KEY = 'SK899987a5997d69c1903655f501c1d928'
SUBACCOUNT_API_SECRET = 'lv4BsBPOx1f1T7C5mvLjiYsgvwa2oikg'

#crontab
CRONJOBS = [
    ('*/1 * * * *', 'cron.my_cron_job')
]

#email notification
EMAIL_SENDER = 'ajithsamplemail@gmail.com'
SENDER_PASSWORD = "Ajith@2021"