# Generated by Django 4.0 on 2021-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='roll',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
