# Generated by Django 3.2.9 on 2021-12-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
