# Generated by Django 3.2.9 on 2021-12-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_status', models.BooleanField(default=False)),
            ],
        ),
    ]
