# Generated by Django 3.2.9 on 2021-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_twilioapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioapi',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
