# Generated by Django 3.2.9 on 2021-12-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_twilioapi_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioapi',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
